### ISSUE TITLE
DNS issue handled improperly from UnknownHostException

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/exchange-android#10]
Android 4.3 Samsung Galaxy S3

java.net.UnknownHostException: Unable to resolve host "slinger-dev.appspot.com": No address associated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
at java.net.InetAddress.getAllByName(InetAddress.java:214)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at edu.cmu.cylab.starslinger.exchange.WebEngine.doPost(WebEngine.java:91)
at edu.cmu.cylab.starslinger.exchange.WebEngine.assignUser(WebEngine.java:148)
at edu.cmu.cylab.starslinger.exchange.ConnectionEngine.assign_user(ConnectionEngine.java:86)
at edu.cmu.cylab.starslinger.exchange.ExchangeController.doRequestUserId(ExchangeController.java:133)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity$AssignUserTask.doInBackground(ExchangeActivity.java:360)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity$AssignUserTask.doInBackground(ExchangeActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Posix.getaddrinfo(Native Method)
at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
... 21 more
https://slinger-dev.appspot.com/assignUser, 36b sent, 0b recv, 0 code, 30119ms
No response from server.

FATAL EXCEPTION: AsyncTask #1
 java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:197)
at android.os.Handler.<init>(Handler.java:111)
at android.app.Dialog.<init>(Dialog.java:111)
at android.app.AlertDialog.<init>(AlertDialog.java:114)
at android.app.AlertDialog$Builder.create(AlertDialog.java:931)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity.onCreateDialog(ExchangeActivity.java:767)
at android.app.Activity.createDialog(Activity.java:1015)
at android.app.Activity.showDialog(Activity.java:3156)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity.showError(ExchangeActivity.java:528)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity.showError(ExchangeActivity.java:519)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity.access$4(ExchangeActivity.java:518)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity$AssignUserTask.doInBackground(ExchangeActivity.java:361)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity$AssignUserTask.doInBackground(ExchangeActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more

**Comment by mwfarb** [comment]
Closed in 09b37d1.
