### ISSUE TITLE
NullPointerException in ExchangeActivity.java:92

### ISSUE THREAD

**Issue by dschuermann** [SafeSlingerProject/exchange-android#8]
Crash report from Google Play:

```
java.lang.NullPointerException
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity$1.run(ExchangeActivity.java:92)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5118)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mwfarb** [comment]
Thanks @dschuermann for posting the error! :+1:

**Comment by dschuermann** [comment]
@mwfarb thanks for fixing. Merged back into OpenKeychain's development branch.
